[package]

name = "lidar"
version = "0.0.1"
authors = ["Tomoya Kitazato <t-kitazato@mcl.iis.u-tokyo.ac.jp>"]

[dependencies]
byteorder="1.1.0"
chrono = "0.4.0"
getopts = "0.2.14"
num = "0.1.40"
serde = "1.0.11"
serde_derive = "1.0.11"
serde_yaml = "0.7.1"
time = "0.1.38"